### ISSUE TITLE
Failed to install S3M

### ISSUE THREAD

**Issue by siddiquimohsin** [BorgwardtLab/S3M#5]
When we run the following command:
```
$ sudo apt install s3m-latest.deb
```
It gave me the error:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package s3m-latest.deb
E: Couldn't find any package by glob 's3m-latest.deb'
```
So, we installed the **s3m-latest.deb** externally and install it.
Now we run the the following command:
```
s3m -i data/example/synthetic.csv -m 15 -o results/example.json
```
But, it gave me the error
```
s3m: error while loading shared libraries: libboost_log.so.1.58.0: cannot open shared object file: No such file or directory
```
So, we go to the [advanced build instructions](docs/advanced_build.md) to solve the above error. we follow the **Building S3M from source** instructions. We installed **cmake**, **libboost-all-dev**, **build-essential**. After that we create the **build** directory and run the following command inside the build directory
```
cmake ../code/cpp/
```
And the command run successfully. After that, we run the **make** command but it gave the error
```
$ make
Consolidate compiler generated dependencies of target s3m
[  4%] Building CXX object CMakeFiles/s3m.dir/source/TimeSeries.cc.o
In file included from /home/mohsin-siddiqui/Desktop/S3M/code/cpp/source/TimeSeries.cc:2:
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh: In function ‘T convert(const S&, bool&)’:
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh:109:21: error: ‘numeric_limits’ is not a member of ‘std’
  109 |       result = std::numeric_limits<T>::infinity();
      |                     ^~~~~~~~~~~~~~
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh:109:37: error: expected primary-expression before ‘>’ token
  109 |       result = std::numeric_limits<T>::infinity();
      |                                     ^
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh:109:40: error: ‘::infinity’ has not been declared
  109 |       result = std::numeric_limits<T>::infinity();
      |                                        ^~~~~~~~
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh:111:22: error: ‘numeric_limits’ is not a member of ‘std’
  111 |       result = -std::numeric_limits<T>::infinity();
      |                      ^~~~~~~~~~~~~~
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh:111:38: error: expected primary-expression before ‘>’ token
  111 |       result = -std::numeric_limits<T>::infinity();
      |                                      ^
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh:111:41: error: ‘::infinity’ has not been declared
  111 |       result = -std::numeric_limits<T>::infinity();
      |                                         ^~~~~~~~
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh:113:21: error: ‘numeric_limits’ is not a member of ‘std’
  113 |       result = std::numeric_limits<T>::quiet_NaN();
      |                     ^~~~~~~~~~~~~~
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh:113:37: error: expected primary-expression before ‘>’ token
  113 |       result = std::numeric_limits<T>::quiet_NaN();
      |                                     ^
/home/mohsin-siddiqui/Desktop/S3M/code/cpp/include/Utilities.hh:113:40: error: ‘::quiet_NaN’ has not been declared
  113 |       result = std::numeric_limits<T>::quiet_NaN();
      |                                        ^~~~~~~~~
make[2]: *** [CMakeFiles/s3m.dir/build.make:188: CMakeFiles/s3m.dir/source/TimeSeries.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:102: CMakeFiles/s3m.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```
So, we have tried another way that is **Building with Docker**. we build the docker image by the following command,
```
docker build -t s3m_container -f code/cpp/packages/DOCKER/Dockerfile .
```
But it gives the pip version error.

**Comment by Pseudomanifold** [comment]
I just pushed a fix for the advanced building instructions, please try that again (after updating the repository). Concerning the Docker issues, I need more details to understand what error you are talking about. If the issue has been rectified, please close the ticket here.

**Comment by siddiquimohsin** [comment]
I run the docker build command and it gave me the following error
```
Collecting numpy (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/42/38/775b43da55fa7473015eddc9a819571517d9a271a9f8134f68fb9be2f212/numpy-1.23.5.tar.gz (10.7MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-htrjy449/numpy/setup.py", line 64
        raise RuntimeError(f'Cannot parse version {FULLVERSION}')
                                                               ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-htrjy449/numpy/
You are using pip version 8.1.1, however version 22.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1

```
I just check my pip version
```
$ pip -V
pip 22.3.1 from /home/mohsin-siddiqui/.local/lib/python3.10/site-packages/pip (python 3.10)
```
I use correct pip version so, how can this error be found?

**Comment by Pseudomanifold** [comment]
Has your original issue with building `S3M` manually been rectified? The docker image is a different problem altogether; notice that the `pip` version is referring to the version inside the Docker container, not the external version.

**Comment by Pseudomanifold** [comment]
Following up on this. If your original issue with building `S3M` has not been rectified, please re-open the issue. For the Docker problems—in case those are still relevant—please open a separate issue.

**Comment by siddiquimohsin** [comment]
I reinstall the docker, but the above error still occurred.

**Comment by Pseudomanifold** [comment]
Does the manual installation work? Please open a separate issue for the Docker problems.
